apiVersion: v1
kind: Service
metadata:
  name: clickrank-service
  labels:
    app: clickrank
spec:
  selector:
    app: clickrank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
