# Redis configuration file
aclfile /usr/local/etc/redis/users.acl
requirepass defaultpassword
# In production, require TLS
# tls-port 6379
# port 0
# tls-cert-file /path/to/redis.crt
# tls-key-file /path/to/redis.key
# tls-ca-cert-file /path/to/ca.crt
