apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clickrank-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: clickrank
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway