input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Add filters here if necessary for log parsing
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "clickrank-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}