/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.clickrank.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ClickEventAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6788814941826701639L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClickEventAvro\",\"namespace\":\"com.example.clickrank.avro\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"query\",\"type\":\"string\"},{\"name\":\"resultId\",\"type\":\"string\"},{\"name\":\"sessionId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClickEventAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClickEventAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ClickEventAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ClickEventAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ClickEventAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ClickEventAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ClickEventAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ClickEventAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ClickEventAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence userId;
  private java.lang.CharSequence query;
  private java.lang.CharSequence resultId;
  private java.lang.CharSequence sessionId;
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClickEventAvro() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param query The new value for query
   * @param resultId The new value for resultId
   * @param sessionId The new value for sessionId
   * @param timestamp The new value for timestamp
   */
  public ClickEventAvro(java.lang.CharSequence userId, java.lang.CharSequence query, java.lang.CharSequence resultId, java.lang.CharSequence sessionId, java.lang.Long timestamp) {
    this.userId = userId;
    this.query = query;
    this.resultId = resultId;
    this.sessionId = sessionId;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return query;
    case 2: return resultId;
    case 3: return sessionId;
    case 4: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.CharSequence)value$; break;
    case 1: query = (java.lang.CharSequence)value$; break;
    case 2: resultId = (java.lang.CharSequence)value$; break;
    case 3: sessionId = (java.lang.CharSequence)value$; break;
    case 4: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'query' field.
   * @return The value of the 'query' field.
   */
  public java.lang.CharSequence getQuery() {
    return query;
  }


  /**
   * Sets the value of the 'query' field.
   * @param value the value to set.
   */
  public void setQuery(java.lang.CharSequence value) {
    this.query = value;
  }

  /**
   * Gets the value of the 'resultId' field.
   * @return The value of the 'resultId' field.
   */
  public java.lang.CharSequence getResultId() {
    return resultId;
  }


  /**
   * Sets the value of the 'resultId' field.
   * @param value the value to set.
   */
  public void setResultId(java.lang.CharSequence value) {
    this.resultId = value;
  }

  /**
   * Gets the value of the 'sessionId' field.
   * @return The value of the 'sessionId' field.
   */
  public java.lang.CharSequence getSessionId() {
    return sessionId;
  }


  /**
   * Sets the value of the 'sessionId' field.
   * @param value the value to set.
   */
  public void setSessionId(java.lang.CharSequence value) {
    this.sessionId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new ClickEventAvro RecordBuilder.
   * @return A new ClickEventAvro RecordBuilder
   */
  public static com.example.clickrank.avro.ClickEventAvro.Builder newBuilder() {
    return new com.example.clickrank.avro.ClickEventAvro.Builder();
  }

  /**
   * Creates a new ClickEventAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClickEventAvro RecordBuilder
   */
  public static com.example.clickrank.avro.ClickEventAvro.Builder newBuilder(com.example.clickrank.avro.ClickEventAvro.Builder other) {
    if (other == null) {
      return new com.example.clickrank.avro.ClickEventAvro.Builder();
    } else {
      return new com.example.clickrank.avro.ClickEventAvro.Builder(other);
    }
  }

  /**
   * Creates a new ClickEventAvro RecordBuilder by copying an existing ClickEventAvro instance.
   * @param other The existing instance to copy.
   * @return A new ClickEventAvro RecordBuilder
   */
  public static com.example.clickrank.avro.ClickEventAvro.Builder newBuilder(com.example.clickrank.avro.ClickEventAvro other) {
    if (other == null) {
      return new com.example.clickrank.avro.ClickEventAvro.Builder();
    } else {
      return new com.example.clickrank.avro.ClickEventAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for ClickEventAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClickEventAvro>
    implements org.apache.avro.data.RecordBuilder<ClickEventAvro> {

    private java.lang.CharSequence userId;
    private java.lang.CharSequence query;
    private java.lang.CharSequence resultId;
    private java.lang.CharSequence sessionId;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.clickrank.avro.ClickEventAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.query)) {
        this.query = data().deepCopy(fields()[1].schema(), other.query);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.resultId)) {
        this.resultId = data().deepCopy(fields()[2].schema(), other.resultId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[3].schema(), other.sessionId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ClickEventAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.clickrank.avro.ClickEventAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.query)) {
        this.query = data().deepCopy(fields()[1].schema(), other.query);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.resultId)) {
        this.resultId = data().deepCopy(fields()[2].schema(), other.resultId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[3].schema(), other.sessionId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'query' field.
      * @return The value.
      */
    public java.lang.CharSequence getQuery() {
      return query;
    }


    /**
      * Sets the value of the 'query' field.
      * @param value The value of 'query'.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder setQuery(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.query = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'query' field has been set.
      * @return True if the 'query' field has been set, false otherwise.
      */
    public boolean hasQuery() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'query' field.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder clearQuery() {
      query = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'resultId' field.
      * @return The value.
      */
    public java.lang.CharSequence getResultId() {
      return resultId;
    }


    /**
      * Sets the value of the 'resultId' field.
      * @param value The value of 'resultId'.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder setResultId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.resultId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'resultId' field has been set.
      * @return True if the 'resultId' field has been set, false otherwise.
      */
    public boolean hasResultId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'resultId' field.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder clearResultId() {
      resultId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sessionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getSessionId() {
      return sessionId;
    }


    /**
      * Sets the value of the 'sessionId' field.
      * @param value The value of 'sessionId'.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder setSessionId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.sessionId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'sessionId' field has been set.
      * @return True if the 'sessionId' field has been set, false otherwise.
      */
    public boolean hasSessionId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sessionId' field.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder clearSessionId() {
      sessionId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder setTimestamp(long value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.example.clickrank.avro.ClickEventAvro.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClickEventAvro build() {
      try {
        ClickEventAvro record = new ClickEventAvro();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.query = fieldSetFlags()[1] ? this.query : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.resultId = fieldSetFlags()[2] ? this.resultId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sessionId = fieldSetFlags()[3] ? this.sessionId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.Long) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClickEventAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClickEventAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClickEventAvro>
    READER$ = (org.apache.avro.io.DatumReader<ClickEventAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeString(this.query);

    out.writeString(this.resultId);

    out.writeString(this.sessionId);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.query = in.readString(this.query instanceof Utf8 ? (Utf8)this.query : null);

      this.resultId = in.readString(this.resultId instanceof Utf8 ? (Utf8)this.resultId : null);

      this.sessionId = in.readString(this.sessionId instanceof Utf8 ? (Utf8)this.sessionId : null);

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 1:
          this.query = in.readString(this.query instanceof Utf8 ? (Utf8)this.query : null);
          break;

        case 2:
          this.resultId = in.readString(this.resultId instanceof Utf8 ? (Utf8)this.resultId : null);
          break;

        case 3:
          this.sessionId = in.readString(this.sessionId instanceof Utf8 ? (Utf8)this.sessionId : null);
          break;

        case 4:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










